# Generated by Django 4.2.10 on 2024-04-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='created',
        ),
    ]
